### ISSUE TITLE
Asset files not loading in kubernetes using a nginx ingress + ssl cert

### ISSUE THREAD

**Issue by aguacate-codes** [frappe/helm#112]
## Description of the issue

- Assets are not loaded in kubernetes (Google cloud cluster)
- Used the template for site ingress

## Steps to reproduce the issue

1. Access to https://cloud001.aguacate.codes/
2. See the consle logs
3. Access to any asset https://cloud001.aguacate.codes/assets/js/bootstrap-4-web.min.js

### Observed result

- GET https://cloud001.aguacate.codes/assets/js/bootstrap-4-web.min.js 404

### Expected result

- All assets loading

### Stacktrace / full error message if available

```
All assets get the following message in browser console 

- GET https://cloud001.aguacate.codes/assets/js/bootstrap-4-web.min.js 404
```

## Context information (for bug reports)

- The certificate is created without issue

**My site ingress .yaml file (belox):**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-cloud001.aguacate.codes
  # Optional Labels
  labels:
    app.kubernetes.io/instance: frappe-bench-0001-erpnext
  annotations:
    # required for cert-manager letsencrypt
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # other annotations as needed, e.g timestamp
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: cloud001.aguacate.codes
    http:
      paths:
      - backend:
          serviceName: frappe-bench-0001-erpnext
          servicePort: 8000
        path: /
  tls:
  - hosts:
    - cloud001.aguacate.codes
    secretName: frappe-bench-0001-erpnext-tls
```
