### ISSUE TITLE
drop site job not working

### ISSUE THREAD

**Issue by DrZoidberg09** [frappe/helm#132]
Hi there,

what an awesome helm chart!

It works very nicely. Especially adding jobs on purpose, whenever needed.

All jobs work fine if enabled in the helm chart, but the drop-site one does not. Just nothing happens. No job gets generated. Create site, migrate, configure, etc. works completely fine.

Do you have any idea? How to debug, if needed?

Thanks!

**Comment by revant** [comment]
make sure `jobs.dropSite.enabled` is set to true for the job to get generated.

It looks for that and only generates the yaml if enabled.

https://github.com/frappe/helm/blob/218a0918d230473150e828ccb6885eb919ba598c/erpnext/templates/job-drop-site.yaml#L1

**Comment by DrZoidberg09** [comment]
Yes, I did. And it works well for all the other jobs, but not for drop-site.

**Comment by revant** [comment]
I created `drop-site-values.yaml`:

```yaml
jobs:
  dropSite:
    enabled: true
    forced: false
    siteName: "erp.cluster.local"

persistence:
  worker:
    storageClass: "nfs"
```

I executed following command:

```shell
helm template erpnext-v13 -n erpnext frappe/erpnext -f tmp/yaml/drop-site-values.yaml -s templates/job-drop-site.yaml > job-drop-site.yaml
```

I got following output in `job-drop-site.yaml`

```yaml
---
# Source: erpnext/templates/job-drop-site.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: erpnext-v13-drop-site-20220805113806
  labels:
    helm.sh/chart: erpnext-5.0.1
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: erpnext-v13
    app.kubernetes.io/version: "v14.0.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: erpnext-v13
      securityContext:
        supplementalGroups:
        - 1000
      containers:
      - name: drop-site
        image: "frappe/erpnext-worker:v14.0.0"
        imagePullPolicy: IfNotPresent
        command: ["bash", "-c"]
        args:
          - bench drop-site
            --root-login=$DB_ROOT_USER
            --root-password=$DB_ROOT_PASSWORD
            --archived-sites-path=archived_sites
            --no-backup
            $(SITE_NAME)
        env:
          - name: "SITE_NAME"
            value: "erp.cluster.local"
          - name: "DB_ROOT_USER"
            value: "root"
          - name: "DB_ROOT_PASSWORD"
            valueFrom:
              secretKeyRef:
                key: mariadb-root-password
                name: erpnext-v13-mariadb
        resources:
            {}
        securityContext:
            capabilities:
              add:
              - CAP_CHOWN
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: assets-cache
            mountPath: /home/frappe/frappe-bench/sites/assets
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      restartPolicy: Never
      volumes:
        - name: assets-cache
          emptyDir: {}
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext-v13
            readOnly: false
        - name: logs
          emptyDir: {}
```
