### ISSUE TITLE
ERPNext Create Site results in Error 404

### ISSUE THREAD

**Issue by Lapotor** [frappe/helm#147]
I tried to create a ERPNext Site but it only creates 404 errors and no new site shows up.

`values.yaml`
```yaml
# See here for more:
# https://github.com/frappe/helm/tree/main/erpnext

# PVC
persistence:
  worker:
    existingClaim: erp-s3-worker-bucket

# Ingress
ingress:
  enabled: true
  ingressName: "sub-domain.tld"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/tls-acme: "true"
  tls:
  - hosts:
      - sub.domain.tld
    secretName: sub-domain-tld-tls
  hosts:
  - host: sub.domain.tld
    paths:
    - path: /
      pathType: ImplementationSpecific

# Jobs
jobs:
  createSite:
    enabled:  true
    siteName: "sub.domain.tld"
    adminPassword: "<AdminPassword>"
```

All worker and jobs running without a error.

The site returns:
```
Not Found

sub.doamin.tld does not exist
```

Does anyone can help me here?
