### ISSUE TITLE
Wrong NodeSelector configuration for socketio

### ISSUE THREAD

**Issue by kirilovvv** [frappe/helm#168]
## Description of the issue
NodeSelector configuration for deployment-socketio does not work - wrong value is passed.
## Context information (for bug reports)
In [deployment-socketio.yaml](https://github.com/frappe/helm/blob/main/erpnext/templates/deployment-socketio.yaml) NodeSelector values are taken from wrong configuration:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
## Steps to reproduce the issue

1. Set NodeSelector values for socketio, e.g. 
```
socketio:
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPU: 75
    targetMemory: 75
  livenessProbe:
    tcpSocket:
      port: 9000
    initialDelaySeconds: 5
    periodSeconds: 10
  readinessProbe:
    tcpSocket:
      port: 9000
    initialDelaySeconds: 5
    periodSeconds: 10
  resources: {}
  nodeSelector: { beta.kubernetes.io/arch: "amd64" }
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    port: 9000
  envVars: []
  initContainers: []
  sidecars: []
```
2. Upgrade erpnext (```helm upgrade ... ```
3. Check NodeSelector field in the Deployment/Pod Spec

### Observed result
The NodeSelector is not defined.
### Expected result
NodeSelector set as follows - beta.kubernetes.io/arch: "amd64"
### Stacktrace / full error message if available
n/a
```
(paste here)
```
