### ISSUE TITLE
Pod not supported on Fargate: invalid SecurityContext fields: Capabilities added: CAP_CHOWN

### ISSUE THREAD

**Issue by philgin** [frappe/helm#182]
## Description of the issue
I'm trying to install erpnext on EKS with Fargate profile testing with minimal configuration:

```
image:
  repository: frappe/erpnext
  tag: v14.30.6
  pullPolicy: IfNotPresent

podSecurityContext:
  supplementalGroups: [1000]

securityContext: {}

persistence:
  worker:
    storageClass: "efs-sc"
    existingClaim: "efs-claim"
```

## Context information (for bug reports)
CAP_CHOWN doesn't seem to be supported on Fargate so I set `securityContext: {}` but somehow it's still gettting set on deployment

## Steps to reproduce the issue

1.  follow steps by @revant https://gist.github.com/revant/1328e3367c3042fd91c447859fb23dd1
2. install helm and add frappe https://helm.erpnext.com
3. `helm install test-app frappe/erpnext -f <the minimal yaml created above to isolate the issue>`

### Observed result
```
fargate-scheduler  Pod not supported on Fargate: invalid SecurityContext fields: Capabilities added: CAP_CHOWN
```

### Expected result
successful deployment

### Stacktrace / full error message if available

```
fargate-scheduler  Pod not supported on Fargate: invalid SecurityContext fields: Capabilities added: CAP_CHOWN
```
