### ISSUE TITLE
Config external redis sentinal and auth

### ISSUE THREAD

**Issue by fzhan** [frappe/helm#216]
Could you please give an example of passing the config to setup redis sentianl using external host with auth?

I currently have
```
redis-cache:
  # https://github.com/bitnami/charts/tree/master/bitnami/redis
  enabled: false
  host: "redis.redis"
  architecture: standalone
  auth:
    enabled: true
    sentinal: true
  master:
    containerPorts:
      redis: 6379 <-- should this be 26379?
    persistence:
      enabled: false

redis-queue:
  # https://github.com/bitnami/charts/tree/master/bitnami/redis
  enabled: false
  host: "redis.redis"
  architecture: standalone
  auth:
    enabled: true
    sentinal: true
  master:
    containerPorts:
      redis: 6379 <-- should this be 26379?
    persistence:
      enabled: false
```
