### ISSUE TITLE
HELM Chart, install apps

### ISSUE THREAD

**Issue by mvarchdev** [frappe/helm#220]
Hello, in HELM chart of ERPNext, there is no payments app installed by default. It is required by some other modules in ERPNext. Is there some possibility to install it in HELM charts? I tried to use `installApps` but this works only with `erpnext` value in the list because only that is installed - so I tried to install apps like bellos but it did not work it still shows error ModuleNotFoundError: No module named 'payments' - So apparently it does not work as expected. Some help?

Tried configuration:
```yaml
  configure:
    enabled: true
    fixVolume: true
    backoffLimit: 0
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}
    envVars: []
    command: ["sh", "-c"]
    args:
      - >
        bench get-app https://github.com/frappe/payments &&
        bench get-app https://github.com/frappe/helpdesk &&
        bench get-app https://github.com/frappe/builder &&
        bench get-app https://github.com/frappe/lending &&
        bench get-app https://github.com/frappe/webshop &&
        bench get-app https://github.com/frappe/print_designer
```

Thanks very much in advance!

Ticket link on frappe helpdesk: https://support.frappe.io/helpdesk/my-tickets/25173
