### ISSUE TITLE
Using a timestamp on objects makes it hard to patch the helm chart

### ISSUE THREAD

**Issue by alfredopalhares** [frappe/helm#223]
Hello,

First of all, thank you for writing this helm chart, its very complete and its for sure helpful on deploying erpnext.

I am having an hard time patching the jobs because of the name having the date https://github.com/frappe/helm/blob/525ace58f629f1281f2f1c1aaa51462e2f4ff187/erpnext/templates/job-create-site.yaml#L5C2-L5C87  in the name makes it hard to do something like:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: erpnext
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: erpnext
      version: "8.1.0"
      sourceRef:
        kind: HelmRepository
        name: frappe-charts
  releaseName: erpnext
  targetNamespace: erpnext
  install:
    createNamespace: true
    disableWait: false
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
  test:
    enable: true
  # https://github.com/frappe/helm/blob/main/erpnext/values.yaml
  values:
    persistence:
      worker:
        enabled: true
        size: 80Gi
        storageClass: openebs-hostpath
        accessModes:
          - ReadWriteMany
    mariadb:
      enabled: false
    postRenderers:
      - kustomize:
          patchesStrategicMerge:
            - kind: Job
              apiVersion: batch/v1
              metadata:
                name: erp-next-new-site-date
              spec:
                template:
                  initContainers:
                    - name: validate-config
                      env:
                        - name: "DB_HOST"
                          valueFrom:
                            secretKeyRef:
                              name: erpnext
                              key: PG_HOST
                        - name: "DB_PORT"
                          valueFrom:
                            secretKeyRef:
                              name: erpnext
                              key: PG_PORT
                  containers:
                    - name: create-site
                      env:
                        - name: "DB_HOST"
                          valueFrom:
                            secretKeyRef:
                              name: erpnext
                              key: PG_HOST
                        - name: "DB_PORT"
                          valueFrom:
                            secretKeyRef:
                              name: erpnext
                              key: PG_PORT

```

What do you suggest in this case? Is there a way to change the name to a fixed position ?
