### ISSUE TITLE
erpnext-conf-bench job failed

### ISSUE THREAD

**Issue by mshtmfv** [frappe/helm#228]
## Description of the issue
Trying to install erpnext on k8s cluster using this helm.

## Context information (for bug reports)
values.yaml:
```
image:
  repository: frappe/erpnext
  tag: v15.48.2
  pullPolicy: IfNotPresent
mariadb:
  enabled: false
postgresql:
  enabled: false
  host: "***"
  primary:
    service:
      ports:
        postgresql: ***
  database: "***"
  auth:
    username: "***"
    password: "***"
redis:
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
persistence:
  worker:
    enabled: true 
    accessModes:
      - ReadWriteMany
    storageClass: csi-s3
    size: 20Gi
nginx:
  service:
    type: LoadBalancer 
    port: 80 
    targetPort: 80  
jobs:
  configure:
    enabled: true
    fixVolume: true
  createSite:
    enabled: true
    siteName: "test.local"
    adminPassword: "***"
    dbType: "postgresql"
    installApps:
      - erpnext

```

### Stacktrace / full error message if available

In logs of job epnext-conf-bench:
```
Usage: bench  set-config [OPTIONS] KEY VALUE
Try 'bench  set-config --help' for help.

Error: Missing argument 'VALUE'.
```
