### ISSUE TITLE
Clear redis-cache on helm upgrades

### ISSUE THREAD

**Issue by revant** [frappe/helm#234]
This fix https://github.com/frappe/frappe_docker/pull/1555 translates to following annotation in `values.yaml`

```yaml
# ... other config
redis-cache:
  master:
    podAnnotations:
      # Change triggers rollout and clears the cache.
      deployed-at: "2025-02-26 10:25:25"
```

Change of annotation will trigger rollout and clear cache. If you do not need to clear cache do not update the annotation.

**Comment by arsanysamuel** [comment]
@revant  Unfortunately I still have this issue that you've mentioned, I've tried adding this to the values with no luck, I've even tried adding an extra command as mentioned [here](https://github.com/bitnami/charts/blob/main/bitnami/redis/README.md) but still the issue persists.
```
redis-cache:
  master:
    podAnnotations:
      deployed-at: '{{ now | date "2006-01-02 15:04:05" }}' 
    preExecCmds:
      - "redis-cli DEL assets_json"
```
Any ideas?
