### ISSUE TITLE
external postgres db

### ISSUE THREAD

**Issue by klahap** [frappe/helm#246]
Hello Frappe Helm team,

I hope you're doing well. I'm attempting to configure Frappe with an external PostgreSQL database but have encountered issues. Here's a summary of my setup and the problem:

In my custom values.yaml, I've set the following:

- external db (dbHost, dbPort, dbRootUser, dbExistingSecret, dbExistingSecretPasswordKey)
- disable maria db ( mariadb.enabled=false )
- set dbType in createSite job (jobs.createSite.dbType=postgres)

full values.yaml: 

```yaml
dbHost: xxx.db.ondigitalocean.com
dbPort: 25060
dbRootUser: doadmin
dbExistingSecret: demo-secrets
dbExistingSecretPasswordKey: db-password

image:
  repository: my-custom/image
  tag: 0.0.1
  pullPolicy: IfNotPresent

persistence:
  worker:
    enabled: true
    # existingClaim: ""
    size: 6Gi
    storageClass: "nfs"
    accessModes:
      - ReadWriteMany

jobs:
  createSite:
    enabled: true
    forceCreate: false
    siteName: "frappe-demo.test.de"
    adminExistingSecret: demo-secrets
    adminExistingSecretKey: site-admin-password
    installApps:
      - "erpnext"
      - "lms"
    dbType: "postgres"
    backoffLimit: 0
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

mariadb:
  enabled: false
```

While all pods and services appear healthy, the frappe-demo.test.de pod logs numerous connection exceptions. It seems to be attempting to connect to MariaDB, resulting in the following error:

`pymysql.err.OperationalError: (2013, 'Lost connection to MySQL server during query')`

full logs: [gunicorn-logs.txt](https://github.com/user-attachments/files/19226914/gunicorn-logs.txt)

Despite these efforts, the application still attempts to connect to MariaDB. I suspect there might be an underlying configuration or compatibility issue causing this behavior. Could you provide guidance on ensuring Frappe uses the external PostgreSQL database as intended?

Thank you for your assistance.
