### ISSUE TITLE
How to restore ERPNext Database

### ISSUE THREAD

**Issue by ajs11174** [frappe/helm#44]
I was able to get the helm chart up and running for ERPNext and I am able to create a backup, however when I restore, only the files are restored. The database is not restored.

Link for reference: https://helm.erpnext.com/kubernetes-resources/create-restore-backups-job

Here are the logs from the restore-backup container 
````
Downloading erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-database.sql.gz
Downloading erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-files.tar
Downloading erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-private-files.tar
Downloading erp.mysite.com/20200707_004431/site_config.json
Overwrite site erp.mysite.com
Extract Database GZip for site erp.mysite.com
sh: 2: -e: not found
sh: 2: -e: not found
sh: 2: -e: not found
sh: 2: -e: not found
Restoring MariaDB
sh: 2: _7033aa8d54d18326: not found
Extracting /home/frappe/backups/erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-private-files.tar
Extracting /home/frappe/backups/erp.mysite.com/20200707_004431/20200707_004431-erp_mysite_com-files.tar
````

I checked Mariadb and database _7033aa8d54d18326 does exist. I'm not sure what is missing.

**Comment by revant** [comment]
I can't tell what's missing.

I'll try on a cluster and comment.

Test seems to pass for docker commands:

https://travis-ci.com/github/frappe/frappe_docker/jobs/358377648#L1942

**Comment by revant** [comment]
I wasn't able to reproduce the issue.

Can you share the resource files?
What version of image are you using?

### Push backup

```sh
❯ k apply -n erpnext -f /tmp/pbjob.yaml
job.batch/push-backups-420 created
❯ kgp -n erpnext -w
NAME                                                   READY   STATUS      RESTARTS   AGE
backup-sites-1532-fd9f9                                0/1     Completed   0          12m
create-new-site-mysite.localhost-jgx8d                 0/1     Completed   0          27m
frappe-bench-erpnext-erpnext-685cf9846b-qtcm2          2/2     Running     1          101m
frappe-bench-erpnext-redis-cache-d4877ff86-bph2t       1/1     Running     0          101m
frappe-bench-erpnext-redis-queue-5dc9d5d95-znpcp       1/1     Running     0          101m
frappe-bench-erpnext-redis-socketio-79bdcbff97-69nlm   1/1     Running     0          101m
frappe-bench-erpnext-scheduler-7cf446cfbb-4n8dw        1/1     Running     0          101m
frappe-bench-erpnext-socketio-6bc54f7df9-k6xnq         1/1     Running     0          101m
frappe-bench-erpnext-worker-d-6674898575-4h76f         1/1     Running     0          101m
frappe-bench-erpnext-worker-l-5b9df457c6-6ds5t         1/1     Running     0          101m
frappe-bench-erpnext-worker-s-8d58cbb44-dqjmd          1/1     Running     0          101m
push-backups-420-4b4k5                                 1/1     Running     0          3s
push-backups-420-4b4k5                                 0/1     Completed   0          6s

❯ kl -n erpnext push-backups-420-4b4k5
Uploading file: /home/frappe/frappe-bench/sites/mysite.localhost/private/backups/20200708_153225-mysite_localhost-database.sql.gz
Uploading file: /home/frappe/frappe-bench/sites/mysite.localhost/site_config.json
Uploading file: /home/frappe/frappe-bench/sites/mysite.localhost/private/backups/20200708_153225-mysite_localhost-files.tar
Uploading file: /home/frappe/frappe-bench/sites/mysite.localhost/private/backups/20200708_153225-mysite_localhost-private-files.tar
push-backup complete
```

### Restore backup (overwrite)

```sh
❯ k apply -n erpnext -f /tmp/restore.yaml
job.batch/restore-backups-420 created
❯ kl -n erpnext restore-backups-420-5b5p8
Downloading mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-database.sql.gz
Downloading mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-files.tar
Downloading mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-private-files.tar
Downloading mysite.localhost/20200708_153225/site_config.json
Overwrite site mysite.localhost
Extract Database GZip for site mysite.localhost
Restoring MariaDB
Extracting /home/frappe/backups/mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-private-files.tar
Extracting /home/frappe/backups/mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-files.tar
```

### Restore backup (fresh)

```sh
❯ k apply -n erpnext -f /tmp/restore.yaml
job.batch/restore-backups-420 created
❯ kl -n erpnext restore-backups-420-4sppc -f
Downloading mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-database.sql.gz
Downloading mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-files.tar
Downloading mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-private-files.tar
Downloading mysite.localhost/20200708_153225/site_config.json
Create site mysite.localhost
Extract Database GZip for site mysite.localhost
Restoring MariaDB
Extracting /home/frappe/backups/mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-private-files.tar
Extracting /home/frappe/backups/mysite.localhost/20200708_153225/20200708_153225-mysite_localhost-files.tar
```

**Comment by ajs11174** [comment]
>What version of image are you using?

I am using v12.10.0 on both the helm chart and all of the backup / restore jobs. 

---
### Backup Job
````
apiVersion: batch/v1
kind: Job
metadata:
  name: backup-sites-manual
  namespace: erpnext
spec:
  backoffLimit: 1
  template:
    spec:
      securityContext:
        supplementalGroups: [1000]
      containers:
        - name: backup-sites
          image: frappe/erpnext-worker:v12.10.0
          args: ["backup"]
          imagePullPolicy: IfNotPresent
          env:
            - name: "WITH_FILES"
              value: "1"
          volumeMounts:
            - name: sites-dir
              mountPath: /home/frappe/frappe-bench/sites
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false
````

### Backup Job Logs
````
database backup taken - ./erp.mysite.com/private/backups/20200708_191656-erp_mysite_com-database.sql.gz - on 2020-07-08 19:16:57.976997
files backup taken - ./erp.mysite.com/private/backups/20200708_191656-erp_mysite_com-files.tar - on 2020-07-08 19:16:57.977317
private files backup taken - ./erp.mysite.com/private/backups/20200708_191656-erp_mysite_com-private-files.tar - on 2020-07-08 19:16:57.977386
````
---

### Upload Job
````
apiVersion: batch/v1
kind: Job
metadata:
  name: push-backups-manual
  namespace: erpnext
spec:
  backoffLimit: 1
  template:
    spec:
      securityContext:
        supplementalGroups: [1000]
      containers:
        - name: push-backups
          image: frappe/erpnext-worker:v12.10.0
          args: ["push-backup"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: sites-dir
              mountPath: /home/frappe/frappe-bench/sites
          env:
            - name: "BUCKET_NAME"
              value: mysite.com
            - name: "REGION"
              value: us-east-2
            - name: "ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: push-backup-s3-secret
            - name: "SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: push-backup-s3-secret
            - name: "ENDPOINT_URL"
              value: https://s3.amazonaws.com
            - name: "BUCKET_DIR"
              value: erpnext/backup
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false
````

### Upload Job Logs
````
Uploading file: /home/frappe/frappe-bench/sites/erp.mysite.com/private/backups/20200708_191656-erp_mysite_com-database.sql.gz
Uploading file: /home/frappe/frappe-bench/sites/erp.mysite.com/site_config.json
Uploading file: /home/frappe/frappe-bench/sites/erp.mysite.com/private/backups/20200708_191656-erp_mysite_com-files.tar
Uploading file: /home/frappe/frappe-bench/sites/erp.mysite.com/private/backups/20200708_191656-erp_mysite_com-private-files.tar
push-backup complete
````

---

### Restore Job
````
apiVersion: batch/v1
kind: Job
metadata:
  name: restore-backups-manual
  namespace: erpnext
spec:
  backoffLimit: 1
  template:
    spec:
      securityContext:
        supplementalGroups: [1000]
      containers:
        - name: restore-backups
          image: frappe/erpnext-worker:v12.10.0
          args: ["restore-backup"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: sites-dir
              mountPath: /home/frappe/frappe-bench/sites
          env:
            - name: "MYSQL_ROOT_PASSWORD"
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mariadb-root-password
            - name: "BUCKET_NAME"
              value: mysite.com
            - name: "ACCESS_KEY_ID"
              valueFrom:
                secretKeyRef:
                  key: accessKey
                  name: push-backup-s3-secret
            - name: "SECRET_ACCESS_KEY"
              valueFrom:
                secretKeyRef:
                  key: secretKey
                  name: push-backup-s3-secret
            - name: "ENDPOINT_URL"
              value: https://s3.amazonaws.com
            - name: "REGION"
              value: us-east-2
            - name: "BUCKET_DIR"
              value: erpnext/backup
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: erpnext
            readOnly: false
````

### Restore Job Logs
````
Downloading erp.mysite.com/20200708_191656/20200708_191656-erp_mysite_com-database.sql.gz
Downloading erp.mysite.com/20200708_191656/20200708_191656-erp_mysite_com-files.tar
Downloading erp.mysite.com/20200708_191656/20200708_191656-erp_mysite_com-private-files.tar
Downloading erp.mysite.com/20200708_191656/site_config.json
Overwrite site erp.mysite.com
Extract Database GZip for site erp.mysite.com
sh: 2: -e: not found
sh: 2: -e: not found
sh: 2: -e: not found
sh: 2: -e: not found
Restoring MariaDB
sh: 2: _7033aa8d54d18326: not found
Extracting /home/frappe/backups/erp.mysite.com/20200708_191656/20200708_191656-erp_mysite_com-private-files.tar
Extracting /home/frappe/backups/erp.mysite.com/20200708_191656/20200708_191656-erp_mysite_com-files.tar
````
