### ISSUE TITLE
How to make a new app and install it on existing site

### ISSUE THREAD

**Issue by premkanish** [frappe/helm#50]
`kubectl exec -it -n <namespace> <helm-frappe-bench-release>-erpnext-erpnext-xxxxxxxxx-xxxxx -c erpnext-python -- docker-entrypoint.sh console site.name.com`

The above command will list the app on the given site.

Apps in this namespace:
frappe, erpnext

```
In [1]: frappe.get_installed_apps()
Out[1]: ['frappe', 'erpnext']
In [2]: exit

```
1. What command to use In order to create a new custom app. 
   In bench we used : `bench new-app {app_name}`

2. Let's say I have custom app from GitHub or other sources and converted the app in to chart. how to add this to already running sites. In bench we used:
`  bench --site [site_name] install-app [app_name]`
           Do I need to run helm upgrade ??

**Comment by revant** [comment]
Everything was designed to be immutable, it is expected to only install apps on site creation. Custom app installation on the fly is not expected.

> What command to use In order to create a new custom app.

- https://github.com/frappe/frappe_docker/blob/develop/docs/custom-apps-for-production.md
- use custom image https://helm.erpnext.com/faq.html#how-do-i-customize-values-for-the-erpnext-helm-chart

> Let's say I have custom app from GitHub or other sources and converted the app in to chart. how to add this to already running sites. In bench we used:
bench --site [site_name] install-app [app_name]
Do I need to run helm upgrade ??

Use console to install app

**Comment by premkanish** [comment]
Hey revant! Thanks for the reply bud.

Let's say I have custom app installed since the beginning and I did some change to its code base, added - deleted few data columns etc. Can i update the new image version through helm upgrade.

**Comment by revant** [comment]
> Hey revant! Thanks for the reply bud.
> 
> Let's say I have custom app installed since the beginning and I did some change to its code base, added - deleted few data columns etc. Can i update the new image version through helm upgrade.

yes you can upgrade, set appropriate values for `migrateJob`, image and tags.

**Comment by premkanish** [comment]
Thanks!

**Comment by mauza** [comment]
I'm running into this currently. I don't see a pod that looks like <helm-frappe-bench-release>-erpnext-erpnext-xxxxxxxxx-xxxxx

```
frappe-bench-mariadb-0     
frappe-bench-redis-socketio-master-0  
frappe-bench-redis-queue-master-0  
frappe-bench-redis-cache-master-0
frappe-bench-erpnext-conf-bench-
frappe-bench-erpnext-worker-d-
frappe-bench-erpnext-socketio-
frappe-bench-erpnext-scheduler-
frappe-bench-erpnext-nginx-
frappe-bench-erpnext-gunicorn-
frappe-bench-erpnext-worker-l
frappe-bench-erpnext-worker-s
```
Those are the pods that are running. I tried to create a migration from the helm migration template but I don't see anything in the created yaml file that mentions the app I want created
```
 # Source: erpnext/templates/job-migrate-site.yaml
 apiVersion: batch/v1
 kind: Job
 metadata:
   name: frappe-bench-erpnext-migrate-20230327195132
   labels:
     helm.sh/chart: erpnext-6.0.16
     app.kubernetes.io/name: erpnext
     app.kubernetes.io/instance: frappe-bench
     app.kubernetes.io/version: "v14.18.3"
     app.kubernetes.io/managed-by: Helm
 spec:
   backoffLimit: 0
   template:
     spec:
       serviceAccountName: frappe-bench-erpnext
       securityContext:
         supplementalGroups:
         - 1000
       containers:
       - name: migrate
         image: "frappe/erpnext:v14.18.3"
         imagePullPolicy: IfNotPresent
         command: ["bash", "-c"]
         args:
           - >
             bench --site $(SITE_NAME) set-maintenance-mode on;
             bench --site $(SITE_NAME) migrate ;
             bench --site $(SITE_NAME) set-maintenance-mode off;
         env:
           - name: "SITE_NAME"
             value: "shop.example.com"
         resources:
           {}
         securityContext:
           capabilities:
             add:
             - CAP_CHOWN
         volumeMounts:
           - name: sites-dir
             mountPath: /home/frappe/frappe-bench/sites
           - name: logs
             mountPath: /home/frappe/frappe-bench/logs
       restartPolicy: Never
       volumes:
         - name: sites-dir
           persistentVolumeClaim:
             claimName: frappe-bench-erpnext
             readOnly: false
         - name: logs
           emptyDir: {}
```
I didn't realize I needed to install paypal_integration until after I had already created my site. I think the path to adding/installing new apps should be simpler.
