### ISSUE TITLE
ERROR 1062 (23000) after add-example-site-job.yaml

### ISSUE THREAD

**Issue by mashkovd** [frappe/helm#62]
Hello,
I install erpnext app in k8s by custom-values.yaml (helm install erpnext_app - frappe/erpnext -f custom-values.yaml)
where Images build from https://github.com/frappe/frappe_docker folder build
and when I use _develop_ Branch erpnext_app good installed, but if i use Branch v11* I have  next problem - 
```
Attempt 1 to connect to mariadb-1593949947.frappe-mariadb.svc.cluster.local:3306
Attempt 1 to connect to base-erpnext-redis-queue:12000
Attempt 1 to connect to base-erpnext-redis-cache:13000
Attempt 1 to connect to base-erpnext-redis-socketio:11000
Connections OK
Created user 36c29e3206c1d751
Created database 36c29e3206c1d751
Granted privileges to user 36c29e3206c1d751 and database 36c29e3206c1d751
Starting database import...
Imported from database /home/frappe/frappe-bench/apps/frappe/frappe/data/Framework.sql
Installing frappe...

Something went wrong:
return code: 1
stdout:
b''
stderr:
b"ERROR 1062 (23000) at line 1: Duplicate entry '%-36c29e3206c1d751' for key 'PRIMARY'\n"
```

Can you help me? 
Is v11* branch (frappe + erpnext) is supported for installed by helm?
thx

**Comment by revant** [comment]
Can you check if the db and user already exists in mariadb.

Either remove the db/user or use FORCE=1 as env variable during site creation

**Comment by mashkovd** [comment]
in my _add-example-site-job.yaml_ FORCE=1

```
        env:
          - name: SITE_NAME
            value: sitename.ru
          - name: DB_ROOT_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: admin
          - name: ADMIN_PASSWORD
            value: admin
          - name: INSTALL_APPS
            value: erpnext
          - name: FORCE
            value: "1"
```
