### ISSUE TITLE
ingress is not working in custom-values.yaml

### ISSUE THREAD

**Issue by mashkovd** [frappe/helm#94]
Hello, 

I set value enabled for ingress is True in file - _https://github.com/frappe/helm/blob/master/erpnext/values.yaml_ like this

ingress:
  enabled: **true**
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
  - host: example.com
    paths:
    - backend:
        serviceName: example.com
        servicePort: 80
      path: /

  tls:
    - hosts:
      - example.com
      secretName: example.com-secret

and after deploy i don't have new  **Ingresses**

Can you tell me what i do wrong?

manifest bellow do it pretty
``` 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example.com
  labels:
    app.kubernetes.io/instance: "FRAPPE_SERVICE"
  annotations:
    # required for cert-manager letsencrypt
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # other annotations as needed, e.g timestamp
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          serviceName: "{{ name }}-erpnext"
          servicePort: 80
        path: /
  tls:
  - hosts:
    - example.com
    secretName: example.com-secret
```
